apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: juphc-tc-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
    - name: dockerconfig-ws
  params:
    - name: build-image
    - name: repo-url
    - name: branch
      default: main
  tasks:
  
    - name: init
      workspaces:
        - name: source
          workspace: pipeline-workspace          
      taskRef:
        name: cleanup
        
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace          
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)
      runAfter:
        - init
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: npm
spec:
- name: npminstall
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: npm
  runAfter:
    - clone
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: jasmine
spec:
- name: tests
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: jasmine
  runAfter:
    - npminstall
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: buildah
spec:
- name: build
  workspaces:
    - name: source
      workspace: pipeline-workspace
  taskRef:
    name: buildah
    kind: ClusterTask
  params:
    - name: IMAGE
      value: "us.icr.io/$(context.pipelineRun.namespace)/$(params.app-name)"
  runAfter:
    - tests


    
